language: java

jdk: oraclejdk7

env: DISPLAY=:99.0

install: true

before_install:
 - sudo apt-get update
 - sudo apt-get install gnome-themes-standard
 - sudo apt-get install metacity
 - sudo apt-get install libwebkit-dev


before_script:
 - chmod +x run-test.sh

script: ./run-test.sh


after_failure:
 - cat /home/travis/build/sashcode/eclipse-plugin-tycho-sample/sample.test.workspace/target/work/data/.metadata/.log.
